### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by tortinator** [potassco/clingoDL#1]
torsten@raz 2030:~/ASP/asprilo> clingoDL action-M.dlp examples/barricade.lp -- -c horizon=2
Answer 1
{ init(object(order,1), [...], minYposition(1) }
with assignment:
Segmentation fault

**Comment by tortinator** [comment]
This is not obtained with  '-c strict=1'

**Comment by rkaminsk** [comment]
We should never just have uploaded binaries here. I am going to put the source code online next week. Which does not have this issue.

PS: Since this is a public issue tracker, you should also attach example files.

**Comment by rkaminsk** [comment]
fixed in master branch
