### ISSUE TITLE
Bug with Preprocessing

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingoDL#13]
[roland.txt](https://github.com/potassco/clingoDL/files/2764189/roland.txt)

Following calls have different results:

clingo-dl roland.txt --stats 0 --text | sed '/^#/ d' | clingo-dl 0
and
clingo-dl roland --stats 0

The theory atom seems to be free although it has been removed by preprocessing.

**Comment by rkaminsk** [comment]
This is a bug in clasp. The aspif program
```
asp 1 0 0
1 1 1 1 0 0
1 1 1 2 0 0
1 0 0 0 1 2
1 0 1 3 0 2 2 -1
1 0 0 0 2 1 -2
9 1 0 1 c
9 5 3 0 0
4 1 a 1 1
4 1 b 1 2
0
```
equivalent to 
```
{a}.
{b}.
:- b.
&c{} :- b, not a.
:- a, not b.
```
should just have one answer set but somehow two are reported. I'll report the issue with clasp.

**Comment by MaxOstrowski** [comment]
Was fixed in clasp.
