### ISSUE TITLE
Easy Propagation

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingoDL#14]
It should be easy to trigger the following propagation.

Given that `x-y <= c` is true:

we can propagate that
`y-x <= -c'` is false for all constraints `y-x <= -c'` where c' > c.

In the strict case we can additionally propagate
`x-y <= c'` is true for all constraints `x-y <= c'` where c' > c.

This could be done independent from the current form of propagation which has a higher complexity and is therefore disabled by default.

**Comment by rkaminsk** [comment]
The `cheap-propagate-alt` branch does something similar. When an edge `(u,v,w)` is added, a shortest path algorithm is run to detect conflicts. During the algorithm, the shortest paths from `u` to all reachable vertices are calculated. For each vertex `s` reached with cost `c`, all edges `(s,u,w')` with `w' + c < 0` are propagated false.

This propagation is only partial but has almost no extra cost. Right now edges are skipped if the lower bound on the distance from `v` to `u` via edge `(u,v,w)` is positive. The test you are suggesting could also be performed in this case but no shortest paths will be computed. Also edges could be propagated false if two reached vertices `s` and `s'` have a backward edge. This test has a higher complexity but we could give it a try.
