### ISSUE TITLE
Improve --propagate-root and --propagate-budget

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingoDL#19]
Whenever --propagate-root and --propagate-budget is used to do some full propagation in the beginning there are two performance flaws:
1. Full propagation needs watches on false literals. These are added for all threads, even if this option is only enabled for one thread
2. After the budget is reached these watches are no longer used but still stay in there. They could be removed again.

**Comment by rkaminsk** [comment]
I addressed point 1 in the code. It *should* work like this. Point 2 is a little more complicated. Something like this might work:

- prop_watches = negative_watches - positive_watches
- when a state leaves the can_propagate state: remove the watches
- when a state enters the can_propagate state: readd the watches

Feel free to try yourself. :smile:

**Comment by rkaminsk** [comment]
I had a look and addressed point 2 too. I hope this works. Please test. I had no example where this had an effect.

**Comment by MaxOstrowski** [comment]
It seems to work fine on my problem.
At least there is no negative effect on the overall propagation speed anymore.
Unfortunately, the positive effects are also not that great on my example but I will investigate in further testing.
Thanks a lot for your effort.

**Comment by rkaminsk** [comment]
It is interesting that this small change has such a big effect. With the examples I had, not a single watch was removed because there was always a positive edge associated. Nevertheless, the corresponding edges do not have to be removed in this case. If this is the same with your problem, then the speed up only comes from removing some constant overhead.

**Comment by rkaminsk** [comment]
Please do some further testing before I put a release on anaconda.
