### ISSUE TITLE
abort in PY and C++ variant

### ISSUE THREAD

**Issue by tortinator** [potassco/clingoDL#2]
torsten@raz 2034:~/ASP/asprilo> clingoDL examples/barricade.lp diff.lp
terminate called after throwing an instance of 'std::logic_error'
  what():  Invalid term cast
Aborted

torsten@bono 2018:~/ASP/asprilo> clingo clingoDL.py diff.lp examples/barricade.lp
clingo version 5.2.1
Reading from clingoDL.py ...
*** ERROR: (clingo): <python>: error: error calling main function:
  Traceback (most recent call last):
    File "<clingoDL.py:1:1-420:6>", line 417, in main
  RuntimeError: Propagator::init: error: error during initialization:
  Traceback (most recent call last):
    File "<clingoDL.py:1:1-420:6>", line 290, in init
  RuntimeError: Invalid term cast

UNKNOWN

Models       : 0+
Calls        : 1
Time         : 0.019s (Solving: 0.00s 1st Model: 0.00s Unsat: 0.00s)
CPU Time     : 0.019s

*Note* Using constants like "eq_dom(x,y,8)." works fine

[dl.zip](https://github.com/potassco/clingoDL/files/1185494/dl.zip)

**Comment by rkaminsk** [comment]
Not really a bug but the very simplistic term evaluation in the propagator. You should not write `&diff { ... } <= -X` but `&diff { ... } <= Y, Y=-X`. This can certainly be made more userfriendly but so far we only cared for the performance of the propagator and did no other polishing whatsoever.
