### ISSUE TITLE
Calling get_bound in print_model results in undefined values when option --quiet=1 is used.

### ISSUE THREAD

**Issue by rkaminsk** [potassco/clingoDL#28]
We have to change how bounds are reported because when clasp reports a model with option `--quiet=1` it does not restore the assignment of the state where the model has been found. We already have a model callback which correctly extends the model with the assignment. Now, we also have to set the current optimization value, there.

**Comment by rkaminsk** [comment]
@MaxOstrowski and @wanko I would simply fix it like this. It is also possible to extract the value of the bound from the terms in the model to keep the previous output. I can merge if you are okay with this. Otherwise, if you prefer this behavior, feel free to implement it. :wink:

**Comment by MaxOstrowski** [comment]
You mean the fix/optimize branch ?
It simply seems to remove the printing of the Optimization value, right ?
I have never used this optimization feature before, so I'm unsure about it.
If anyone has a strong opinion about it I could implement it.
Not printing it does not seem completely right to me... but the old way also was not ideal.

**Comment by rkaminsk** [comment]
> You mean the fix/optimize branch ?

It is just commit linked above.

> It simply seems to remove the printing of the Optimization value, right ?

Yes.

> I have never used this optimization feature before, so I'm unsure about it.
> If anyone has a strong opinion about it I could implement it.

Better wait with this. With the current interfaces it is very annoying to implement.

> Not printing it does not seem completely right to me... but the old way also was not ideal.

In clingo-dl it is always a variable that is minimized. As long as the answer set is shown, the variable will be visible. Additionally, the value will be visible in the statistics. We don't loose anything. It just looked a little nicer before.
