### ISSUE TITLE
Algorithm Improvement II

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingoDL#33]
In propagator.hh ll 378:
`for (auto st_idx : s.outgoing) {`
would it make sense to go only through edges that can actually reach `u` in the full graph.
This could be statically precomputed for every node (complete reachability).

What do you think?

**Comment by rkaminsk** [comment]
One could calculate strongly connected components and ignore edges whose start and end points are in different components. Of course you would need graphs that fall apart in components and have edges from one component to the other. I don't have high hopes that this happens when considering the whole graph. One could of course calculate components on the fly while propagating. But I think this would be too expensive.

**Comment by MaxOstrowski** [comment]
I did not thought about connected components, but just one direction.
If there is a path from a ->* b it does not mean that there exists a path from b ->* a.
Especially not a negative one! So why go to "b" if we will nevery have a chance to find a negative loop back to "a", no matter which atoms are true.

**Comment by rkaminsk** [comment]
Maybe you should think a bit more about what I have written?

**Comment by MaxOstrowski** [comment]
Of course you are right.
I checked on some train examples the number of SCC's.
There are some trivial SCC's (length 1) but usually only one large one.

**Comment by MaxOstrowski** [comment]
Removing the "0" node this large SCC's falls apart into smaller onces.

**Comment by rkaminsk** [comment]
> Removing the "0" node this large SCC's falls apart into smaller onces.

I have very often seen constraints of the form:

    { "0" - start(X) } <= 0 
    { end(X) - "0" } <= bound

If you remove the last one most problems become easy. :smile: If your problem consists of independent subproblems, you could use a different "0" node for each subproblem.

**Comment by MaxOstrowski** [comment]
> If you remove the last one most problems become easy. :smile: 

For sure :laughing: 
You mean that the "0" node unnecessarily combined SCC's ? And we could have independent propagators for each SCC? Could this speed things up? I would try to produce some statistics on the SCC's of the graphs without the "0" node.
Is it ensured that these subproblems are then independent (in terms of DL).

**Comment by rkaminsk** [comment]
> > If you remove the last one most problems become easy. smile
> 
> For sure laughing
> You mean that the "0" node unnecessarily combined SCC's ? And we could have independent propagators for each SCC? Could this speed things up? I would try to produce some statistics on the SCC's of the graphs without the "0" node.
> Is it ensured that these subproblems are then independent (in terms of DL)?

I just make some examples to show what I mean. Assume you have the nodes:

```
problem 1:
a ----- b ----- c

problem 2:
g------\
d ----- e ----- f
         \----- h
```

Here it does not matter how `a` and `g` start relatively to each other because we can shift the starting points, that is the `0` nodes, anyway we like.

To calculate the subproblems, one can remove the `0` node and calculate connected components treating the graph as an undirected graph. Afterward one can readd the removed edges with different `0` nodes to each component again. The propagation algorithm does not have to be changed. Also note that the `0` node is an arbitrary choice. It is possible to do this with any node.

**Comment by MaxOstrowski** [comment]
I found one example with the following stats (without edges to or from 0 (removed 69081 edges)). I still have to look if this is in general the case.
```
The graph has 266758 nodes
The graph has 405367 edges
SCC:
Size: 42
Size: 8
Size: 64
Size: 152
Size: 194
Size: 23
Size: 376
Size: 34
Size: 46
Size: 62
Size: 34
Size: 22
Size: 88
Size: 38
Size: 166113
Size: 149
Size: 39
Size: 125
Size: 39
Size: 33
Size: 15
Size: 63
Size: 64
Size: 34
Size: 6
Size: 34
Size: 113
Size: 37652
Size: 6
Size: 23
Size: 52
Size: 42
Size: 70
Size: 54
Size: 54
Size: 54
Size: 54
Size: 54
Size: 54
Size: 54
Size: 54
Size: 54
Size: 54
Size: 42
Size: 4
Size: 265
Size: 24
Size: 58
Size: 447
Size: 11
Size: 1016
Size: 12
Size: 58
Size: 45
Size: 141
Size: 363
Size: 20
Size: 340
Size: 201
Size: 58
Size: 306
Size: 25
Size: 16
Size: 14
Size: 33
Size: 14
Size: 14
The graph has 56903 SCCs, 67 non-trivial
CC:
Size: 205217
Size: 56118
Size: 414
Size: 161
Size: 59
Size: 3289
Size: 18
Size: 38
Size: 172
Size: 361
Size: 361
Size: 361
Size: 189
The graph has 13 CCs, 13 non-trivial
```

**Comment by rkaminsk** [comment]
> I found one example with the following stats (without edges to or from 0 (removed 69081 edges)). I still have to look if this is in general the case.

You read my comment about *connected* versus *strongly connected* components?

**Comment by MaxOstrowski** [comment]
How could I do so?
1. I would need to have the CC's as input to the encoding.
2. Ah, I see. I just use a different constant, like 1000 instead of node 0 for this cc and also add 1000 to all unary constraints. Doesn't this get simplified back to 0 again?

**Comment by MaxOstrowski** [comment]
@wanko does this mean that the subproblems (trains) are truly independent? Is there any connection I don't see?

**Comment by wanko** [comment]
This would not surprise me for trains that don't share any routes.

**Comment by rkaminsk** [comment]
> How could I do so?
> 
>     1. I would need to have the CC's as input to the encoding.
> 
>     2. Ah, I see. I just use a different constant, like 1000 instead of node 0 for this cc and also add 1000 to all unary constraints. Doesn't this get simplified back to 0 again?

Call it what ever you like: `null(1)`, `null(2)`, null(3).

**Comment by rkaminsk** [comment]
> This would not surprise me for trains that don't share any routes.

Maybe you can solve these problems independently from each other. This is typically much better than solving them all together.

**Comment by MaxOstrowski** [comment]
That would be the goal in our case.Nevertheless I think that the decomposition is nearly for free (linear init for cc computation) and could help in some problems. It maybe the case that the original problem is not always splittable if there is a connection of the subproblems via asp atoms.I still would like to check if we have several CC's on other benchmark classes.-------- Originalnachricht --------Betreff: Re: [potassco/clingoDL] Algorithm Improvement II (#33)Von: Roland Kaminski An: potassco/clingoDL Cc: Max Ostrowski ,Author 

This would not surprise me for trains that don't share any routes.

Maybe you can solve these problems independently from each other. This is typically much better than solving them all together.

**Comment by MaxOstrowski** [comment]
I tried adding the cc's as facts and replaced every "0" variable in the diff constraint by null(cc_number) in the encoding.
```
{ "0" - start(X) } <= 0 
{ end(X) - "0" } <= bound
```
Unfortunately, I do get -501869 as a result for all these null(cc_number) variables. So my whole solution seems to be shifted down. Any ideas what am I doing wrong ?

**Comment by MaxOstrowski** [comment]
It works. I startet a simple example with partial+ (and limited number of conflicts as the example is big).

Old Version:
```
  DifferenceLogic
    Time init(s): 2.47515
    Mutexes    : 0
    [Thread 0]
      Propagation(s): 52.8308
      Dijkstra(s): 0
      Undo(s)  : 4.48008
      True edges: 0
      False edges: 0
      False edges (inverse): 1.29998e+07
      False edges (partial): 15948
      False edges (partial+): 19123
      Edges added: 1.76307e+07
      Edges skipped: 1.72994e+07
      Edges propagated: 0
      Cost consistency: 2.49084e+07
      Cost forward: 0
      Cost backward: 0

```

CC Version:
```
DifferenceLogic
  Time init(s): 2.51954
  Mutexes    : 0 
  [Thread 0]
    Propagation(s): 36.3214
    Dijkstra(s): 0 
    Undo(s)  : 4.33289
    True edges: 0 
    False edges: 0 
    False edges (inverse): 1.29998e+07
    False edges (partial): 15948
    False edges (partial+): 19123
    Edges added: 1.76307e+07
    Edges skipped: 1.72994e+07
    Edges propagated: 0 
    Cost consistency: 1.6372e+07
    Cost forward: 0 
    Cost backward: 0 
```

So propagation times reduced. I expect similar but less significant reduction with --propagate=no.

**Comment by MaxOstrowski** [comment]
Done in branch scc, ready to be merged into wip.

**Comment by MaxOstrowski** [comment]
I just found out that there is no normalization for other constants. So the following example:
```
&diff { 7 - a } <= -5.
&diff { 7 - b } <= -5.
```
does produce only one cc. This should be changed, I'll look into it.

**Comment by rkaminsk** [comment]
> I just found out that there is no normalization for other constants. So the following example:
> 
> ```
> &diff { 7 - a } <= -5.
> &diff { 7 - b } <= -5.
> ```
> 
> does produce only one cc. This should be changed, I'll look into it.

You might be misinterpreting things here. If you write `&diff { 2 - 1 } <= 0`, then you will get a valid assignment to the variables `2` and `1` assigning both to 0. That being said, it would be nice to handle constants in difference constraints in an *more intuitive* way. While you are at it, we should also support the relations `<`, `>`, `>=`, `=`, and `!=`. I would also allow for using variables in bounds. All I would require is that there are two variables and a minus operation. This way a user can encode his problem in the most straightforward way. Then we should get rid of the strict option and just treat theory atoms in the body as strict (you can also shift in the head for integrity constraints).

Coming back to the splitting of components, I think that we can split at arbitrary nodes. It does not have to be the zero node. But this is not exhibited in your example above because right now you have to write it as
```
&diff { 0 - a } <= -12.
&diff { 0 - b } <= -12.
```

**Comment by MaxOstrowski** [comment]
Opened a new PR #37 for this.

**Comment by MaxOstrowski** [comment]
Sorry, messed things up with guthub. It's now Issue #38.
