### ISSUE TITLE
Algorithm Improvement III

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingoDL#36]
There is an upper bound of the weighted length any cycle free path in the difference logic graph can have.
```
max(N,M) :- node(N), M = #max {W : edge(_,N,W), W > 0 }.
bound(M) :- M = #max {W : max(N,W)}.
```
Another approximation could also be dynamically computed by simply summing up all active positive edges.
In a lot of examples the "0" node is the only one with positives incoming edges.
The graph traversal algorithms could probably benefit from this upper bound ?

**Comment by rkaminsk** [comment]
I don't see how. The traversal algorithms already stop as soon as possible.

**Comment by MaxOstrowski** [comment]
OK, closing it then.
