### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingoDL#38]
- [x] disallow variables like 1, 2, 3 ... (`&diff { 7 - a } <= -5.`) and translate them to `&diff { 0 - a } <= -12.`
 - [x] support relations `<`, `>`, `>=`, `=`, and `!=`
 - [x] allow for using variables in bounds
 - [x] get rid of the strict option and just treat theory atoms in the body as strict (you can also shift in the head for integrity constraints).

(did'nt manage to open draft PR against wip)

**Comment by wanko** [comment]
>     * [ ]  disallow variables like 1, 2, 3 ... (`&diff { 7 - a } <= -5.`)
Makes sense.

>     * [ ]  support relations `<`, `>`, `>=`, `=`, and `!=`
Will you give the user a reasonable warning if they write "x=-y"? Also, what will be the epsilon for real numbers?

> 
>     * [ ]  allow for using variables in bounds
What do you mean?
> 
>     * [ ]  get rid of the strict option and just treat theory atoms in the body as strict (you can also shift in the head for integrity constraints).
Love it.
> 
> 
> (did'nt manage to open draft PR against wip)
Yes my confusion was tangible.

**Comment by rkaminsk** [comment]
> > ```
> > * [ ]  disallow variables like 1, 2, 3 ... (`&diff { 7 - a } <= -5.`)
> > ```
> 
> Makes sense.

I would not forbid it. I would automatically rewrite it to `&diff { null - a } <= -13.`

> > ```
> > * [ ]  support relations `<`, `>`, `>=`, `=`, and `!=`
> > ```
> 
> Will you give the user a reasonable warning if they write "x=-y"? Also, what will be the epsilon for real numbers?

`x=-y` is an illegal constraint and should lead to an error message.

Otherwise, can we just ignore real numbers? Does anyone use those? In any case I think that with real numbers the user has to know what he is doing. Even writing `a <= x` and `a >= x` in two separate constraints in the current implementation can lead to trouble.

> > ```
> > * [ ]  allow for using variables in bounds
> > ```
> 
> What do you mean?

Being allowed to write the very intuitive constraint `x + 10 <= y`. :wink:

> > ```
> > * [ ]  get rid of the strict option and just treat theory atoms in the body as strict (you can also shift in the head for integrity constraints).
> > ```
> 
> Love it.
> 
> > (did'nt manage to open draft PR against wip)
> > Yes my confusion was tangible.

**Comment by wanko** [comment]
> 
> 
> > > ```
> > > * [ ]  disallow variables like 1, 2, 3 ... (`&diff { 7 - a } <= -5.`)
> > > ```
> > 
> > 
> > Makes sense.
> 
> I would not forbid it. I would automatically rewrite it to `&diff { null - a } <= -13.`
> 
> > > ```
> > > * [ ]  support relations `<`, `>`, `>=`, `=`, and `!=`
> > > ```
> > 
> > 
> > Will you give the user a reasonable warning if they write "x=-y"? Also, what will be the epsilon for real numbers?
> 
> `x=-y` is an illegal constraint and should lead to an error message.
> 
> Otherwise, can we just ignore real numbers? Does anyone use those? In any case I think that with real numbers the user has to know what he is doing. Even writing `a <= x` and `a >= x` in two separate constraints in the current implementation can lead to trouble.

I would be for dropping real as it is the easier case anyway and it would simplify the code. Also, agreed on delivering a sensible ERROR message. I just worry that if the syntax looks so similar to CASP, people think in CASP terms.

> 
> > > ```
> > > * [ ]  allow for using variables in bounds
> > > ```
> > 
> > 
> > What do you mean?
> 
> Being allowed to write the very intuitive constraint `x + 10 <= y`. 😉
> 
Same comment as above, I am not the biggest fan of stearing away from the difference constraint syntax, but I'll allow it as you do all the coding work anyway. ;)
> > > ```
> > > * [ ]  get rid of the strict option and just treat theory atoms in the body as strict (you can also shift in the head for integrity constraints).
> > > ```
> > 
> > 
> > Love it.
> > > (did'nt manage to open draft PR against wip)
> > > Yes my confusion was tangible.

**Comment by rkaminsk** [comment]
> I would be for dropping real as it is the easier case anyway and it would simplify the code. Also, agreed on delivering a sensible ERROR message. I just worry that if the syntax looks so similar to CASP, people think in CASP terms.

To be honest, I would like to have clingo-dl as part of clingcon in the long run. But I am with you in the sense that I want to keep the `&diff` constraints in a form that can be handled efficiently without having to introduce order variables and that we get the one-to-one correspondence between answer sets and assignments.

**Comment by MaxOstrowski** [comment]
> I would not forbid it. I would automatically rewrite it to &diff { null - a } <= -13.

That was what I meant, I will clarify this.

> To be honest, I would like to have clingo-dl as part of clingcon in the long run. But I am with you in the sense that I want to keep the &diff constraints in a form that can be handled efficiently without having to introduce order variables and that we get the one-to-one correspondence between answer sets and assignments.

We just have to be careful that this can be done to optimize performance but we need to preserve the semantics of the two systems (CASP, LOWEST_POSSIBLE_SOLUTION).

**Comment by rkaminsk** [comment]
> > To be honest, I would like to have clingo-dl as part of clingcon in the long run. But I am with you in the sense that I want to keep the &diff constraints in a form that can be handled efficiently without having to introduce order variables and that we get the one-to-one correspondence between answer sets and assignments.
> 
> We just have to be careful that this can be done to optimize performance but we need to preserve the semantics of the two systems (CASP, LOWEST_POSSIBLE_SOLUTION).

I am fully with you on this one.

**Comment by wanko** [comment]
Agreed.

**Comment by MaxOstrowski** [comment]
So do we drop support for real numbers ? Than I would add it to the list.

@rkaminsk Does it make sense to add these things to clingoDL now or is this something that should be done when combining the two systems...

**Comment by rkaminsk** [comment]
If there is something you can do quickly why not put it in clingo-dl. But I would not invest too much time here.

**Comment by MaxOstrowski** [comment]
Regarding point 1 & 2 I do not see a way to do it leightweight but would copy parse_constraint_elem from clingcon and fit it for clingoDL. Do you think this is the way to go ? Otherwise we would miss out on things like `&diff{ a - (3 + x -5*Y)} <= Y :- dom(Y)`.

**Comment by rkaminsk** [comment]
You can copy from clingcon. When merging both code bases. The clingo-dl code will reuse the parsing code from clingcon anyway.

**Comment by MaxOstrowski** [comment]
Trying to reuse some of clingcon's code but this ends in a mess as long as we have reals "e.g." `&diff {a- "0.5"} <= "0.7"` as coefficients would need to be doubles and I do not know how to rewrite the `safe_xxx` methods for this. Any advice ?

**Comment by rkaminsk** [comment]
`std::enable_if` is your friend. :wink: 

```cpp
template <typename Int, std::enable_if_t<std::is_integral_v<Int>, int> = 0>         
Int safe_add(Int a, Int b) {                                                               
    if (b > 0) {                                                                                                                                                                                                                                                               
        if (a > std::numeric_limits<Int>::max() - b) {                                                                                                                                                                                                                         
            throw std::overflow_error("integer overflow");                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                                                                      
    }                                                                                                                                                                                                                                                                          
    else if (b < 0) {                                                                                                                                                                                                                                                          
        if (a < std::numeric_limits<Int>::min() - b) {                                                                                                                                                                                                                         
            throw std::underflow_error("integer underflow");                                                                                                                                                                                                                   
        }                                                                                                                                                                                                                                                                      
    }                                                                                                                                                                                                                                                                          
    return a + b;                                                                                                                                                                                                                                                              
}                                                                                                                                                                                                                                                                              
  
template <typename Float, std::enable_if_t<std::is_floating_point_v<Float>, int> = 0>  
Float safe_add(Float a, Float b) {                                                                                                                                                                                                      
    return a + b;                                                                                                                                                                                                                       
}
```

**Comment by MaxOstrowski** [comment]
Thanks, i would had simply overloaded safe_add for int and float...
But my original problem was more about the safety_check on the doubles :) but if it is ok to leave it out, I'm fine with it...

**Comment by rkaminsk** [comment]
I might have used the functions for 32 and 64 bit integers so you would have to provide two overloads (maybe not during parsing). Don't waste your time on overflow checks for doubles. We are going to remove this anyway.

**Comment by MaxOstrowski** [comment]
I would need some help with this template magic in the normalize branch:
https://github.com/potassco/clingoDL/blob/normalize/libclingo-dl/clingo-dl/propagator.hh

ll 1586 and 1595
the enable_if fails with the template parameter T and I don't know why.

**Comment by rkaminsk** [comment]
You cannot specialize like this. The workaround is easy though. Also you should not use C++17 in clingo-dl because it is written in C++14.

```cpp
template <class F, class N, typename std::enable_if<std::is_integral<N>::value, int>::type = 0>
Clingo::Symbol evaluate_(Clingo::TheoryTerm const &a, Clingo::TheoryTerm const &b, F &&f) const {
    auto ea = evaluate(a);
    check_syntax(ea.type() == Clingo::SymbolType::Number);
    auto eb = evaluate(b);
    check_syntax(eb.type() == Clingo::SymbolType::Number);
    return Clingo::Number(f(ea.number(), eb.number()));
}

template <class F, class N, typename std::enable_if<std::is_floating_point<N>::value, int>::type = 0>
Clingo::Symbol evaluate_(Clingo::TheoryTerm const &a, Clingo::TheoryTerm const &b, F &&f) const {
    auto ea = evaluate(a);
    check_syntax(ea.type() == Clingo::SymbolType::String);
    auto eb = evaluate(b);
    check_syntax(eb.type() == Clingo::SymbolType::String);
    return Clingo::String(std::to_string(f(std::stod(ea.string()), std::stod(eb.string()))).c_str());
}

template <class F>
Clingo::Symbol evaluate(Clingo::TheoryTerm const &a, Clingo::TheoryTerm const &b, F &&f) const {
    return evaluate_<F, T>(a, b, std::forward<F>(f));
}


```

**Comment by MaxOstrowski** [comment]
thanks a lot

**Comment by MaxOstrowski** [comment]
I have a question regarding `false_lit_edges_`.
https://github.com/potassco/clingoDL/blob/wip/libclingo-dl/clingo-dl/propagator.hh
ll.1170-1175
```
        if (add) {
            false_lit_to_edges_.emplace(-lit, id);
            if (conf_.strict) {
                false_lit_to_edges_.emplace(lit, id);
            }
        }
```
I'm confused that in the strict case id is added to `false_lit_to_edges_`, doesn't it has to be id+1 (the edge with the opposite direction?
The id of the reversed edge is never used again, and I'm currently trying to create a function that adds `b => x - y <= c` and `-b => y - c <= -c-1` separately.

**Comment by rkaminsk** [comment]
Yes, it has to be `id+1`. To be honest, I never tested the strict option. There was no example for it. All tests I did are on the examples in the examples folder. When you add the edge during parsing, you can probably simplify this code away.

**Comment by MaxOstrowski** [comment]
Could someone explain to me how clingoDL with rdl works ? There seems to be no option to give real numbers as weights yet, but weight is stored as T during parsing.

**Comment by rkaminsk** [comment]
The `get_weight` function should parse doubles from strings like `"1.234"`.

**Comment by MaxOstrowski** [comment]
Seems that in https://github.com/potassco/clingoDL/blob/master/libclingo-dl/src/clingo-dl.cc
ll 98 is wrong and should be double.

**Comment by rkaminsk** [comment]
> Seems that in https://github.com/potassco/clingoDL/blob/master/libclingo-dl/src/clingo-dl.cc
> ll 98 is wrong and should be double.

Just go ahead and fix these things. I never tested the --rdl option.

**Comment by MaxOstrowski** [comment]
While trying to copy the shifting of constraints I stumbled upon the fold expressions you used.
These are only available in C++17.
I must admit that I'm a bit puzzled of how to translate them into C++14 :(

**Comment by rkaminsk** [comment]
Just write the recursive equivalent.

**Comment by MaxOstrowski** [comment]
Started copying all necessary functions for shifting from clingcon in branch [shift](https://github.com/potassco/clingoDL/tree/shift).
I do not understand this error quite, any ideas ?

```
Fehler: keine passende Funktion für Aufruf von »TheoryRewriter::visit(Clingo::AST::Statement&, Clingo::AST::Rule&)«
   41 |         t.visit(std::forward<N>(node), std::forward<V>(value));
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In Datei, eingebunden von /home/ostrowsk/work/krbiz/gitpotassco/clingoDL/libclingo-dl/src/clingo-dl.cc:26:
/home/ostrowsk/work/krbiz/gitpotassco/clingoDL/libclingo-dl/clingo-dl/propagator.hh:226:17: Anmerkung: Kandidat: »template<class Lit> static void TheoryRewriter::visit(Lit&, Clingo::AST::TheoryAtom&)«
  226 |     static void visit(Lit &node, Clingo::AST::TheoryAtom &atom) {
```

**Comment by rkaminsk** [comment]
It looks like the compile is expecting a function `TheoryRewriter::visit(Clingo::AST::Statement&, Clingo::AST::Rule&)` but only finds a function `TheoryRewriter::visit(Lit &node, Clingo::AST::TheoryAtom &atom)`? Have you checked that the required function is available?

**Comment by MaxOstrowski** [comment]
It is not available. But as I copied the code from clingcon I'm not sure it actually HAS to be available... as clingcon can do without and I wanna do exactly the same here.

**Comment by rkaminsk** [comment]
I cannot help you like this. Can you point me to a place where I can have a look.

**Comment by MaxOstrowski** [comment]
Thanks a lot, this helped. I was puzzled by too much of this template action.

**Comment by MaxOstrowski** [comment]
Atoms in the body are now strict, atoms in the head non-strict.
Difference constraints over reals are only allowed in the head (non-strict).
I removed the strict option.

Featurewise this should be it, more refactoring is needed.

**Comment by rkaminsk** [comment]
> Featurewise this should be it, more refactoring is needed.

Great. Can you have a look at the issues I mentioned above? Just open a PR when I shall have another look.
