### ISSUE TITLE
Invalid term cast error in dev build on Anaconda

### ISSUE THREAD

**Issue by daveraja** [potassco/clingoDL#42]
I just updated to the latest clingo-dl **dev** build on anaconda and I am now getting the error: 

     *** ERROR: (clingo-dl): Invalid term cast

Looking further it seems to be caused by having tuples as theory terms; so `foo(a,b)` is ok but `(a,b)` is not. The following highlights the issue:

      inst((a,b),6).         % Error
      inst(foo(a,b),6).      % Ok

      &diff{ X-0 } <= V :- inst(X,V).

This has only crept in with the very latest linux build. So the previous `v1.1.1` build `hcebc348_4` was fine but  the current `v1.1.1` build `hcebc348_5` causes the error.

**Comment by rkaminsk** [comment]
I can only imagine that this is due to Max' latest patch. @MaxOstrowski can you have a look.

**Comment by MaxOstrowski** [comment]
Yes, it is on my agenda.
Unfortunately, I can not promise to find the time until next month.

**Comment by daveraja** [comment]
No worries. I can downgrade to v1.1.0 for the time being.

**Comment by daveraja** [comment]
Wow. This month has gone very fast indeed! :)

Thanks.

**Comment by MaxOstrowski** [comment]
Sometimes miracles happen.
@rkaminsk still needs to approve and merge it...
