### ISSUE TITLE
non-strict inequality

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingoDL#45]
What would be the expected outcome for:
```
{var("z")}.        
&diff{"x"} != 5 :- not var("z"). 
```
Currently it is:
```
{z}
{x=6}
{z, x=6}
{x=0}
{z,x=0}
```

After removing the duplicates bug as in https://github.com/potassco/clingcon/issues/43 it would be:
```
{x=6}
{x=0}
{z}
```
Still, the x=6 does not seem right ? I don't know.

**Comment by rkaminsk** [comment]
> ```
> {x=6}
> {x=0}
> {z}
> ```
> 
> Still, the x=6 does not seem right ? I don't know.

It is what the translation gives. I think it is okay. We can either make it smaller than 5 or larger. It is just that the choice literal is hidden.
