### ISSUE TITLE
Faster builds with travis

### ISSUE THREAD

**Issue by rkaminsk** [potassco/clingoDL#8]
If you use anaconda as for example telingo does, you should be able to reduce the build times to 2 or 3 minutes for travis.

https://github.com/potassco/telingo/blob/master/.travis.yml

**Comment by MaxOstrowski** [comment]
I'm struggling a bit with conda.
I tried to build the respective files ( https://github.com/MaxOstrowski/conda )
but conda seems to accept only complete lower case names for packes, source and binaries.
Currently the naming convention is "clingoDL". What should we do about it.

**Comment by MaxOstrowski** [comment]
Can I safely upload this development version to the anaconda server ?
The Version number is 1.0.0, can it be overridden with a different **build** number later?
Thx

**Comment by rkaminsk** [comment]
I would say we just use the lower case name and be done with it.

**Comment by rkaminsk** [comment]
You can increase the build number later. Conda will then update the packages even though they have the same build number. But just check how I did this for telingo. I put the packages in the dev channel. I would suggest to put the clingodl packages in the dev channel too.

https://anaconda.org/potassco/

**Comment by rkaminsk** [comment]
I personally don't like adding non-numbers to a version (and I am not alone). That's why I recommended to put it in a "beta" channel (which you should do regardless of what you decide to use as a version name).

**Comment by pluehne** [comment]
Good thinking :+1:. Putting the preview version in a “beta” channel makes it clear that the package is released for testing purposes only, so nobody will complain should the package be overwritten silently later.
